
if __name__ == '__main__':
	numers = str()
	m = int()
	x = int()
	i = int()
	pr1 = str()
	pr2 = str()
	producto3 = str()
	print("Porfavor ingrese su primer producto para almacenar")
	pr1 = input()
	print("Por favor ingrese su segundo producto para almacenar")
	pr2 = input()
	print("Por favor ingrese su tercer producto para almacenar")
	pr3 = input()
	print("a continuacion sus productos se mostraran desde el ultimo en almacenar hasta el primero")
print("valor:",pr3)
print("valor:",pr2)
print("valor:",pr1)